// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agriculture.proto

package bw.project.smartfarming;

public final class BW_SmartFarmingServiceImpl {
  private BW_SmartFarmingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_farm_TractorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_farm_TractorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_farm_TractorReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_farm_TractorReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_farm_IrrigationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_farm_IrrigationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_farm_IrrigationReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_farm_IrrigationReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_farm_LivestockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_farm_LivestockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smart_farm_LivestockReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smart_farm_LivestockReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021agriculture.proto\022\nsmart_farm\".\n\016Tract" +
      "orRequest\022\014\n\004name\030\001 \001(\t\022\016\n\006number\030\002 \001(\005\"" +
      " \n\014TractorReply\022\020\n\010response\030\001 \001(\t\"1\n\021Irr" +
      "igationRequest\022\014\n\004name\030\001 \001(\t\022\016\n\006number\030\002" +
      " \001(\005\"#\n\017IrrigationReply\022\020\n\010response\030\001 \001(" +
      "\t\"0\n\020LivestockRequest\022\014\n\004name\030\001 \001(\t\022\016\n\006n" +
      "umber\030\002 \001(\005\"\"\n\016LivestockReply\022\020\n\010respons" +
      "e\030\001 \001(\t2\373\001\n\017SmartAutoSystem\022G\n\rtractorSe" +
      "nsor\022\032.smart_farm.TractorRequest\032\030.smart" +
      "_farm.TractorReply\"\000\022P\n\020irrigationSensor" +
      "\022\035.smart_farm.IrrigationRequest\032\033.smart_" +
      "farm.IrrigationReply\"\000\022M\n\017livestockSenso" +
      "r\022\034.smart_farm.LivestockRequest\032\032.smart_" +
      "farm.LivestockReply\"\000B7\n\027bw.project.smar" +
      "tfarmingB\032BW_SmartFarmingServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smart_farm_TractorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smart_farm_TractorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_farm_TractorRequest_descriptor,
        new java.lang.String[] { "Name", "Number", });
    internal_static_smart_farm_TractorReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smart_farm_TractorReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_farm_TractorReply_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_smart_farm_IrrigationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smart_farm_IrrigationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_farm_IrrigationRequest_descriptor,
        new java.lang.String[] { "Name", "Number", });
    internal_static_smart_farm_IrrigationReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smart_farm_IrrigationReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_farm_IrrigationReply_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_smart_farm_LivestockRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smart_farm_LivestockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_farm_LivestockRequest_descriptor,
        new java.lang.String[] { "Name", "Number", });
    internal_static_smart_farm_LivestockReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smart_farm_LivestockReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smart_farm_LivestockReply_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
