// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agriculture.proto

package bw.project.smartfarming;

public interface TractorReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_farm.TractorReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
