// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agriculture.proto

package bw.project.smartfarming;

public interface TractorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_farm.TractorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 number = 2;</code>
   */
  int getNumber();
}
